# Generated by Django 4.2.6 on 2023-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
    ]
