# Generated by Django 4.2.6 on 2023-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_logo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_logo', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
