# Generated by Django 4.2.6 on 2023-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cust_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
