# Generated by Django 4.2.6 on 2023-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_cust', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
