# Generated by Django 4.2.6 on 2023-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_happy_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoodie', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polo', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_serv', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Round_neck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_neck', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
